name: tobefunded
favicon: null
layout_spectrum: 0.014719278551638126
typography_spectrum: 0.3944
title: 'Thoughts on the earliest stages of startups '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#080808'
    - '#2f4a67'
    - '#576f87'
    - '#feffbb'
    - '#b1b3b2'
  brandStrength: 0.20048841508105397
  lightness: 0.7134644703473896
  saturation: 0.02277901885099709
  rhythmicContrast: 0.2041315007954836
purpose: []
